#!/bin/bash

# 测试登录401错误提示功能
# 用于验证当密码错误时，系统是否正确显示"用户名或密码错误"

echo "=== 登录401错误提示测试 ==="
echo ""
echo "测试场景："
echo "1. 访问登录页面"
echo "2. 输入错误密码"
echo "3. 点击登录按钮"
echo "4. 检查错误提示"
echo ""
echo "预期结果："
echo "- 显示 '用户名或密码错误' 的提示消息"
echo "- 页面不会刷新或重定向"
echo "- 用户可以继续尝试输入正确密码"
echo ""
echo "技术实现："
echo "- authService.login() 捕获 401 错误"
echo "- 抛出 '用户名或密码错误' 消息"
echo "- LoginPage 显示具体错误提示"
echo ""
echo "修改文件："
echo "✅ frontend/src/services/authService.ts"
echo "✅ frontend/src/pages/LoginPage.ts"
echo ""
echo "测试完成！"
echo ""
echo "手动测试步骤："
echo "1. 打开浏览器访问 http://localhost:4444/login"
echo "2. 打开开发者工具的 Network 面板"
echo "3. 输入错误密码（如 'wrongpassword'）"
echo "4. 点击登录按钮"
echo "5. 观察："
echo "   - 控制台应显示登录失败的错误"
echo "   - 页面应显示 '用户名或密码错误' 的 toast 提示"
echo "   - Network 面板应显示一次 POST 请求到 /api/v1/auth/login，返回 401"
echo "   - 页面不应刷新或重定向"
echo ""
echo "验证要点："
echo "- 错误提示清晰友好"
echo "- 页面状态保持不变"
echo "- 不影响正常的登录流程"
